[project]
name = "Plutos"
version = "0.1.0"
description = "High performance trading bot"
dependencies = [
    "fastapi",
    "uvicorn",
    "pandas",
    "databento",
    "numpy",
    "httpx",
    "websocket-client",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "ruff"
]

[tool.ruff]
line-length = 120
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
# Definiert den Suchpfad für deine Source-Dateien (ersetzt das -o pythonpath=src)
pythonpath = ["src"]

# Packt deine Coverage-Befehle und die ausführliche Anzeige (-v) direkt in den Standard-Lauf
addopts = "-v --cov=src --cov-report=term-missing --cov-report=xml"
